"""Deterministic Jinja2 renderer for ``report/<locale>/news-YYYYMMDD.md``.

Spec: ``design/sourcedata-layout.md §Skill decomposition`` and
``§Markdown rendered shape (after)``.

Reads the per-date sourcedata JSON files
(``app/sourcedata/<date>/{predictions,headlines,change_log,news_section}.json``,
plus the locale variants under ``app/sourcedata/locales/<date>/<locale>/``)
and returns/writes the rendered markdown. The renderer is pure prose:
no ``plain_language`` keyword, no legacy stream-letter vocabulary, no
``- because:``/``- given:``/``- so_that:``/``- landing:`` bullet keys,
no ``**Summary:**`` parser anchor — those internal field names live in
the JSON, not in the rendered markdown.

Public API:

  * :func:`render_day(repo_root, date_iso, locale) -> str` — assemble.
  * :func:`render_and_write(repo_root, date_iso, locale) -> Path` —
    atomic write + post-write-integrity.

Soft-imports ``jinja2``: the legacy ``cli update`` markdown-fallback
path doesn't need this module, so the import error is deferred to the
first ``render_day`` call rather than module-load time.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from app.skills.ingest_sourcedata import date_dir, locale_date_dir
from app.skills.sourcedata_schemas import (
    ChangeLogFile,
    HeadlinesFile,
    NewsSectionFile,
    PredictionsFile,
)


# AI-notice strings per locale — spec
# `design/scheduled/2_future_prediction-writer-rules.md §AI-notice header`.
# News reuses the same locale strings (the only difference is the H1
# above; both report kinds carry the same notice block under it).
_AI_NOTICE = {
    "en": (
        "<!-- ai-notice -->\n"
        "> **Note:** The articles and summaries on this page are "
        "generated by Anthropic's Claude (a generative AI)."
    ),
    "ja": (
        "<!-- ai-notice -->\n"
        "> **ご注意:** 本ページの記事および要約は、Anthropic 社の生成AI"
        "「Claude」によって作成されています。"
    ),
    "es": (
        "<!-- ai-notice -->\n"
        "> **Nota:** Los artículos y resúmenes de esta página son "
        "generados por Claude (IA generativa) de Anthropic."
    ),
    "fil": (
        "<!-- ai-notice -->\n"
        "> **Paalala:** Ang mga artikulo at buod sa pahinang ito ay "
        "nilikha ng generative AI na Claude ng Anthropic."
    ),
}


def _ai_notice(locale: str) -> str:
    return _AI_NOTICE.get(locale, _AI_NOTICE["en"])


def _coverage_window(date_iso: str) -> str:
    """3-day rolling window stanza for the news-report header."""
    import datetime as _dt

    d = _dt.date.fromisoformat(date_iso)
    start = (d - _dt.timedelta(days=2)).isoformat()
    return f"{start} to {date_iso} (3-day rolling window)"


def _load_jsons(repo_root: Path, date_iso: str, locale: str) -> dict:
    """Load the four input JSON files for a given (date, locale) pair.

    Locale != "en" reads from ``app/sourcedata/locales/<date>/<locale>/``;
    "en" reads from ``app/sourcedata/<date>/`` directly. Files that
    don't exist are skipped — the renderer still produces (empty)
    sections for missing data.
    """
    if locale == "en":
        base = date_dir(repo_root, date_iso)
    else:
        base = locale_date_dir(repo_root, date_iso, locale)

    out: dict = {}
    pred_path = base / "predictions.json"
    if pred_path.is_file():
        out["predictions"] = PredictionsFile.from_dict(
            _read_json(pred_path)
        ).to_dict()
    else:
        out["predictions"] = {"date": date_iso, "predictions": []}

    hl_path = base / "headlines.json"
    if hl_path.is_file():
        out["headlines"] = HeadlinesFile.from_dict(
            _read_json(hl_path)
        ).to_dict()
    else:
        out["headlines"] = {"date": date_iso, "technical": [], "plain": []}

    cl_path = base / "change_log.json"
    if cl_path.is_file():
        out["change_log"] = ChangeLogFile.from_dict(
            _read_json(cl_path)
        ).to_dict()
    else:
        out["change_log"] = {"date": date_iso, "vs_date": "", "items": []}

    ns_path = base / "news_section.json"
    if ns_path.is_file():
        out["news_section"] = NewsSectionFile.from_dict(
            _read_json(ns_path)
        ).to_dict()
    else:
        out["news_section"] = {"date": date_iso, "sections": []}

    return out


def _read_json(path: Path) -> dict:
    import json

    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Jinja2 environment + filters
# ---------------------------------------------------------------------------


def _build_env():
    try:
        import jinja2
    except ImportError as e:  # pragma: no cover - exercised only when jinja2 absent
        raise RuntimeError(
            "render_news_md requires jinja2. Install via "
            "`pip install jinja2` or add the optional 'render' extra."
        ) from e

    template_dir = Path(__file__).resolve().parents[1] / "templates"
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(template_dir)),
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    env.filters["render_citations"] = _render_citations
    env.filters["indent_block"] = _indent_block
    env.filters["table_cell"] = _table_cell
    env.filters["strip_lead_emdash"] = _strip_lead_emdash
    return env


def _render_citations(citations) -> str:
    """Render a list of {label, url} dicts as a comma-joined link list."""
    if not citations:
        return ""
    parts = []
    for c in citations:
        label = c.get("label", "") if isinstance(c, dict) else ""
        url = c.get("url", "") if isinstance(c, dict) else ""
        parts.append(f"[{label}]({url})")
    return ", ".join(parts)


def _indent_block(text: str, n: int) -> str:
    """Indent every line after the first by n spaces.

    Used for prose blocks that sit inside numbered list items so the
    rendered markdown nests cleanly. The first line is already at the
    correct column from the surrounding template.
    """
    if not text:
        return ""
    pad = " " * n
    lines = text.splitlines()
    if not lines:
        return ""
    return lines[0] + "\n" + "\n".join(pad + ln for ln in lines[1:])


def _table_cell(text: str) -> str:
    """Escape pipes + collapse newlines so a string is safe in a md table cell."""
    if text is None:
        return ""
    return str(text).replace("\n", " ").replace("|", "\\|").strip()


def _strip_lead_emdash(text: str) -> str:
    """Normalize em-dashes in headline body text.

    Some legacy headline bodies start with ``— ``; the template now
    inserts the em-dash itself between lead and body, so a leading dash
    in the body would render as ``— —``. Trim it so the rendered output
    is ``**lead** — body`` as the spec specifies.

    Also collapses internal ``— —`` (and longer runs) to a single ``—``
    — these arise when the LLM author wrote a double em-dash as a
    section break inside the body prose; the rendered surface should
    have at most a single em-dash between any two clauses.
    """
    if not text:
        return ""
    s = str(text).lstrip()
    # Strip one leading em-dash + optional whitespace.
    if s.startswith("— "):
        s = s[2:].lstrip()
    elif s.startswith("—"):
        s = s[1:].lstrip()
    # Collapse runs of em-dashes inside the body (e.g. "— —" → "—").
    import re as _re
    s = _re.sub(r"—(\s*—)+", "—", s)
    return s


# ---------------------------------------------------------------------------
# Public renderer
# ---------------------------------------------------------------------------


def render_day(repo_root, date_iso: str, locale: str = "en") -> str:
    """Assemble and return the rendered markdown for a single date.

    Does not write to disk. Use :func:`render_and_write` for the writer
    flow that also runs ``post-write-integrity``.
    """
    repo_root = Path(repo_root)
    env = _build_env()
    template = env.get_template("news.md.j2")

    data = _load_jsons(repo_root, date_iso, locale)
    ctx = {
        "date_iso": date_iso,
        "date_compact": date_iso.replace("-", ""),
        "coverage_window": _coverage_window(date_iso),
        "locale": locale,
        "ai_notice_block": _ai_notice(locale),
        **data,
    }
    rendered = template.render(**ctx)
    # Normalize line endings + trim runs of >2 blank lines that Jinja2
    # whitespace control sometimes leaves behind.
    rendered = rendered.replace("\r\n", "\n").replace("\r", "\n")
    while "\n\n\n\n" in rendered:
        rendered = rendered.replace("\n\n\n\n", "\n\n\n")
    if not rendered.endswith("\n"):
        rendered += "\n"
    return rendered


def output_path(repo_root, date_iso: str, locale: str) -> Path:
    """Return the canonical output path for a (date, locale) pair."""
    repo_root = Path(repo_root)
    return (
        repo_root
        / "report"
        / locale
        / f"news-{date_iso.replace('-', '')}.md"
    )


def _write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        os.replace(tmp, path)
    except Exception:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


def render_and_write(repo_root, date_iso: str, locale: str = "en") -> Path:
    """Render + atomically write + run post-write-integrity (kind=news).

    On post-write-integrity failure, the markdown stays on disk so the
    caller can inspect it; the function raises ``RuntimeError`` with
    the integrity report as the message. The write is atomic — if
    rendering fails, the existing file (if any) is untouched.
    """
    rendered = render_day(repo_root, date_iso, locale)
    out = output_path(repo_root, date_iso, locale)
    _write_atomic(out, rendered)
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "app.skills.post_write_integrity",
            "--kind",
            "news",
            "--path",
            str(out),
        ],
        cwd=str(Path(repo_root)),
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"post-write-integrity failed for {out}:\n"
            f"{proc.stdout}\n{proc.stderr}"
        )
    return out


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(
        description="Render a news report from sourcedata JSON."
    )
    p.add_argument("--date", required=True, help="ISO date, e.g. 2026-05-04")
    p.add_argument("--locale", default="en", choices=["en", "ja", "es", "fil"])
    p.add_argument(
        "--repo-root",
        default=".",
        help="Repository root (defaults to cwd).",
    )
    p.add_argument(
        "--write",
        action="store_true",
        help="Write to report/<locale>/news-YYYYMMDD.md (else stdout).",
    )
    args = p.parse_args(argv)

    if args.write:
        out = render_and_write(args.repo_root, args.date, args.locale)
        print(f"OK wrote {out}")
        return 0
    print(render_day(args.repo_root, args.date, args.locale), end="")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
