// AI-notice strings per locale — spec
// design/scheduled/2_future_prediction-writer-rules.md §AI-notice header.
// News and future-prediction reports share the same block (only the H1
// above differs). Ported from render_news_md.py / render_future_prediction_md.py.

const AI_NOTICE: Record<string, string> = {
  en:
    '<!-- ai-notice -->\n'
    + "> **Note:** The articles and summaries on this page are "
    + "generated by Anthropic's Claude (a generative AI).",
  ja:
    '<!-- ai-notice -->\n'
    + '> **ご注意:** 本ページの記事および要約は、Anthropic 社の生成AI'
    + '「Claude」によって作成されています。',
  es:
    '<!-- ai-notice -->\n'
    + '> **Nota:** Los artículos y resúmenes de esta página son '
    + 'generados por Claude (IA generativa) de Anthropic.',
  fil:
    '<!-- ai-notice -->\n'
    + '> **Paalala:** Ang mga artikulo at buod sa pahinang ito ay '
    + 'nilikha ng generative AI na Claude ng Anthropic.',
};

export function aiNotice(locale: string): string {
  return AI_NOTICE[locale] ?? AI_NOTICE.en;
}

/** The future-prediction module carries its own copy of the table
 * upstream, and its `fil` string ends with a trailing newline the news
 * copy lacks (render_future_prediction_md.py line 54). Kept verbatim —
 * the fil FP goldens carry the resulting extra blank line. */
export function aiNoticeFp(locale: string): string {
  const base = aiNotice(locale);
  return locale === 'fil' ? base + '\n' : base;
}

export const LOCALES = ['en', 'ja', 'es', 'fil'] as const;
